# Generated by Django 5.1.4 on 2025-01-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curation',
            name='points',
        ),
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
