# Generated by Django 5.1.4 on 2025-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0005_curation_sub_title_curation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
